security:
    encoders:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User : plaintext


    providers:
        users_in_memory:
            memory:
                users:
                    admin: { password: '123', roles: 'ROLE_ADMIN'}

        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        dev:
            anonymous: lazy
            provider: users_in_memory
            http_basic:
                realm: My Secured Area
    access_control:
         - { path: ^/*, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
