
weather_in_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:cityAction

create:
  path: /create
  controller: App\Controller\WeatherController:index

edit-city:
  path: /edit-city/{country}/{city}
  controller: App\Controller\WeatherController:cityEdit

delete-city:
  path: /delete-city/{country}/{city}
  controller: App\Controller\WeatherController:deleteCity

edit-measurement:
  path: /edit-measurement/{id}
  controller: App\Controller\WeatherController:measurementEdit

delete-measurement:
  path: /delete-measurement/{id}
  controller: App\Controller\WeatherController:deleteMeasurement

home:
  path: /
  controller: App\Controller\WeatherController:homeAction

any:
  path: /{token}
  controller: App\Controller\WeatherController:homeAction
  requirements:
    token: .*