
weather_in_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:cityAction

create:
  path: /create
  controller: App\Controller\WeatherController:index

cities:
  path: /cities
  controller: App\Controller\WeatherController:citiesListAction

measurements:
  path: /measurements
  controller: App\Controller\WeatherController:measurementsListAction

home:
  path: /
  controller: App\Controller\WeatherController:homeAction